# tablist
[plugin]
    enabled=true

# Global tablist
[global-tablist]
    enabled=false

[tablist-header-footer]
    enabled=false
    # If you are unsure how to hanle new lines, take a look at https://toml.io/en/ or just use \n
    header="<color:#ff0048>Welcome to </color><color:#ff5900>example network!</color>"
    footer="<light_purple>have fun!</light_purple>"

[list-player-current-server]
    enabled=false

[list-player-luckperm-rank]
    enabled=false

[luckperm-rank-color]
    list=["owner","admin","staff"]
    owner="0xCF00DB"
    admin="0x473EC8"
    staff="0x9B0010"

[developer-info]
    config-version=0.2